name: Matrix Demo
on: push
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [14, 15]
        operating-system: [ubuntu-latest, windows-latest]
        include:
          - node-version: 14
            operating-system: ubuntu-latest
          - node-version: 15
            operating-system: windows-latest
        exclude:
          - node-version: 14
            operating-system: windows-latest
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build website
        run: npm ci
      - name: Run build command
        run: npm run build
